question_data = [
  {"text": "A slug's blood is green.", "answer": "True"},
  {"text": "The loudest animal is the African Elephant.", "answer": "False"},
  {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
  {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
  {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, "
           "you are free to take it home to eat.", "answer": "True"},
  {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
   "answer": "False"},
  {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
  {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
  {"text": "Google was originally called 'Backrub'.", "answer": "True"},
  {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
  {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
  {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]

question_data_2 = [
  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
   "question": "English new wave musician Gary Numan founded the video game development company Facepunch Studios in March 2009.",
   "correct_answer": "False", "incorrect_answers": ["True"]},
  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
   "question": "Undertale; is an RPG created by Toby Fox and released in 2015.", "correct_answer": "True",
   "incorrect_answers": ["False"]},
  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
   "question": "There are 6 legendary cards in Clash Royale;.",
   "correct_answer": "False", "incorrect_answers": ["True"]},
  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
   "question": "Deus Ex (2000) does not feature the World Trade Center "
               "because it was destroyed by terrorist attacks according to the games plot.",
   "correct_answer": "True", "incorrect_answers": ["False"]},
  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
   "question": "In the Half-Life series, H.E.V stands for Hazardous Evasiveness Vest",
   "correct_answer": "False", "incorrect_answers": ["True"]},
  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
   "question": "The end credits sequence in Grand Theft Auto 5 is over half an hour long.", "correct_answer": "True",
   "incorrect_answers": ["False"]},
  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
   "question": "In Pok&eacute;mon, Arbok evolves into Seviper.",
   "correct_answer": "False", "incorrect_answers": ["True"]},
  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
   "question": "Metal Gear Solid 3: Snake Eater was released in 2004.", "correct_answer": "True",
   "incorrect_answers": ["False"]},
  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
   "question": "Sonic the Hedgehog 2 originally was going to have a time travel system.",
   "correct_answer": "True", "incorrect_answers": ["False"]},
  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
   "question": "Codemasters is the developer of the Gran Turismo series.", "correct_answer": "False",
   "incorrect_answers": ["True"]}]
