question_data = [
  {"text": "A slug's blood is green.", "answer": "True"},
  {"text": "The loudest animal is the African Elephant.", "answer": "False"},
  {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
  {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
  {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, "
           "you are free to take it home to eat.", "answer": "True"},
  {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
   "answer": "False"},
  {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
  {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
  {"text": "Google was originally called 'Backrub'.", "answer": "True"},
  {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
  {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
  {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]

question_data_2 = [
  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
   "question": "English new wave musician Gary Numan founded the video game development company Facepunch Studios in March 2009.",
   "correct_answer": "False", "incorrect_answers": ["True"]},
  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
   "question": "Undertale; is an RPG created by Toby Fox and released in 2015.", "correct_answer": "True",
   "incorrect_answers": ["False"]},
  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
   "question": "There are 6 legendary cards in Clash Royale;.",
   "correct_answer": "False", "incorrect_answers": ["True"]},
  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
   "question": "Deus Ex (2000) does not feature the World Trade Center "
               "because it was destroyed by terrorist attacks according to the games plot.",
   "correct_answer": "True", "incorrect_answers": ["False"]},
  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
   "question": "In the Half-Life series, H.E.V stands for Hazardous Evasiveness Vest",
   "correct_answer": "False", "incorrect_answers": ["True"]},
  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
   "question": "The end credits sequence in Grand Theft Auto 5 is over half an hour long.", "correct_answer": "True",
   "incorrect_answers": ["False"]},
  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
   "question": "In Pok&eacute;mon, Arbok evolves into Seviper.",
   "correct_answer": "False", "incorrect_answers": ["True"]},
  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
   "question": "Metal Gear Solid 3: Snake Eater was released in 2004.", "correct_answer": "True",
   "incorrect_answers": ["False"]},
  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
   "question": "Sonic the Hedgehog 2 originally was going to have a time travel system.",
   "correct_answer": "True", "incorrect_answers": ["False"]},
  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
   "question": "Codemasters is the developer of the Gran Turismo series.", "correct_answer": "False",
   "incorrect_answers": ["True"]}]

question_data_3 = [
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "Typewriter is the longest word that can be typed using only the first row on a QWERTY keyboard.",
   "correct_answer": "True", "incorrect_answers": ["False"]},
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "Coca-Colas original colour was green.", "correct_answer": "False", "incorrect_answers": ["True"]},
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "The US emergency hotline is 911 because of the September 11th terrorist attacks.",
   "correct_answer": "False", "incorrect_answers": ["True"]},
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "The vapor produced by e-cigarettes is actually water.", "correct_answer": "False",
   "incorrect_answers": ["True"]},
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "The sum of all the numbers on a roulette wheel is 666.",
   "correct_answer": "True", "incorrect_answers": ["False"]},
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "There are 86400 seconds in a day.", "correct_answer": "True", "incorrect_answers": ["False"]},
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "An eggplant is a vegetable.", "correct_answer": "False", "incorrect_answers": ["True"]},
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "The bikini is named after the Bikini Atoll, "
               "an island where the United States conducted tests on atomic bombs.",
   "correct_answer": "True", "incorrect_answers": ["False"]},
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "Cucumbers are usually more than 90% water.", "correct_answer": "True", "incorrect_answers": ["False"]},
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "You are allowed to sell your soul on eBay.", "correct_answer": "False", "incorrect_answers": ["True"]},
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "Kissing someone for one minute burns about 2 calories.", "correct_answer": "True",
   "incorrect_answers": ["False"]},
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "Sitting for more than three hours a day can cut two years off a persons life expectancy.",
   "correct_answer": "True", "incorrect_answers": ["False"]},
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "The French word to travel is Travail", "correct_answer": "False",
   "incorrect_answers": ["True"]},
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "The French word for glass is glace.",
   "correct_answer": "False", "incorrect_answers": ["True"]},
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "Albert Einstein had trouble with mathematics when he was in school.", "correct_answer": "False",
   "incorrect_answers": ["True"]},
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "Fast food restaurant chains Carls Jr. and Hardees are owned by the same company.",
   "correct_answer": "True", "incorrect_answers": ["False"]},
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "Santa Claus is a variety of melon.", "correct_answer": "True",
   "incorrect_answers": ["False"]},
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "Haggis is traditionally ate on Burns Night.",
   "correct_answer": "True", "incorrect_answers": ["False"]},
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "Francis Bacon died from a fatal case of pneumonia while "
               "he was attempting to preserve meat by stuffing a chicken with snow.",
   "correct_answer": "True", "incorrect_answers": ["False"]},
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "Popcorn was invented in 1871 by Frederick W. Rueckheim in the USA "
               "where he sold the snack on the streets of Chicago.",
   "correct_answer": "False", "incorrect_answers": ["True"]},
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "The British organisation CAMRA stands for The Campaign for Real Ale.", "correct_answer": "True",
   "incorrect_answers": ["False"]},
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "The commercial UK channel ITV stands for International Television.",
   "correct_answer": "False", "incorrect_answers": ["True"]},
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "The pickled gherkin was first added to hamburgers "
               "because a US health law required all fast-food to include a source of Vitamin C.",
   "correct_answer": "False", "incorrect_answers": ["True"]},
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo. is a grammatically correct sentence.",
   "correct_answer": "True", "incorrect_answers": ["False"]},
  {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
   "question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.", "correct_answer": "True",
   "incorrect_answers": ["False"]}]
